### ISSUE TITLE
Possible to use the FNA audio library in a win forms project?

### ISSUE THREAD

**Issue by DannyGlover** [FNA-XNA/FNA#103]
I don't see FNA on Nuget.

I'm doing some low level audio work and seen as XNA can't be used in a win forms project anymore, i'm looking for an alternative.

FNA seems to fit the bill, and I only require use of its audio libraries. Is this possible to integrate into an existing win forms project?

Thanks for all your hard work

**Comment by flibitijibibo** [comment]
FNA probably won't ever be on NuGet. Meh.

The audio system can definitely be used on its own; just be sure to call `Microsoft.Xna.Framework.FrameworkDispatcher.Update()` on startup and then once per frame, as that updates the audio device and its resources (such as DynamicSoundEffectInstance objects). You may also want to assign callbacks to FNALoggerEXT on startup so that FNAPlatform doesn't get tripped:

```
FNALoggerEXT.LogInfo = Console.WriteLine;
FNALoggerEXT.LogWarn = Console.WriteLine;
FNALoggerEXT.LogError = Console.WriteLine;
```

After that, all that should be required from FNA is the OpenAL Soft library, and everything else can be ignored.

**Comment by DannyGlover** [comment]
That's wonderful!

Is the installation to do this as simple as copying the dll's as dependencies to my existing win forms project?

Sorry for all the newb questions. Really appreciate the help

**Comment by flibitijibibo** [comment]
Yup, that should be all. Reference FNA.dll and copy in SDL2.dll and soft_oal.dll and all should be well.

**Comment by DannyGlover** [comment]
Thanks @flibitijibibo - I'll give it a go and report back.

**Comment by DannyGlover** [comment]
@flibitijibibo Sorry, one last thing. I'm not seeing FNA.dll in the finallibs package which was available on the website. Where can I grab that?

**Comment by flibitijibibo** [comment]
Build FNA.sln from the latest zipfile and it should pop out. I don't ship prebuilt binaries of FNA.dll since I normally encourage developers to integrate the csproj into their solution, rather than using a DLL, so they can debug on their own in the event of an issue. It only depends on System.dll, so it's not one of Those Projects(TM) that has more dependencies than lines of code...

**Comment by DannyGlover** [comment]
Thanks. Didn't manage to compile the code due to several source files being marked as missing by visual studio.

Guess today isn't my day.

Was also unsuccessful in adding references to SDL/oal as: A reference to LIBNAMEHERE could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component.

**Comment by flibitijibibo** [comment]
SDL/oal are native libraries, so you don't have to link to those. You can just throw them in the output directory and FNA will pick them up.

As for the missing FNA files... did you `git clone` or `git clone --recursive`? The missing files are likely just the submodules in the lib/ folder.

**Comment by DannyGlover** [comment]
That got it. Right, time to test referencing :)

**Comment by DannyGlover** [comment]
@flibitijibibo You sir are a gentleman and a scholar.

It works wonderfully! I tried to port the same project to monogame and it failed miserably. FNA works right out of the box.

I wasted the whole day on convoluted attempts, and it took me less than 10 minutes to get up and running with FNA. 

Thank you so much

**Comment by flibitijibibo** [comment]
Neato! Let me know if you run into any boogs later on.
