### ISSUE TITLE
AccessViolationException loading MGFX

### ISSUE THREAD

**Issue by BenTackett** [FNA-XNA/FNA#110]
I'm trying to load an effect, compiled to an xnb file using the latest release build of the monogame content builder (MGCB.exe), but it throws an AccessViolationException and writes the following error to the log:

    MOJOSHADER_parseEffect Error: Out of memory

Here is the hlsl source: https://gist.github.com/BenTackett/10ed8ae067543eec7edd545dbcf9b8bf

I'm using the *s_4_0_level_9_3 profile because that is what worked on monogame, but just plain *s_4_0 also has this issue. And, as far as I can tell, I'm supposed to be using *s_4_0.

If it's worth anything, here's the compiled xnb file too: https://www.dropbox.com/s/3j6n0gvxwytwovk/BasicSprite.xnb?dl=0

**Comment by flibitijibibo** [comment]
Please read the documentation before using FNA:

https://github.com/FNA-XNA/FNA/wiki/2:-Building-with-FNA#2a-about-effect-support

Right now we only have support for SM3, though I wonder if 4_0_level_9_3 would be easy to parse since it's not actually SM4. Compile with `fxc.exe /T fx_2_0` and see if it still builds, it might need 3_0 instead.

**Comment by BenTackett** [comment]
I switched to fx_2_0 and it seems to work. Thanks, and sorry for not reading the documentation more carefully

**Comment by flibitijibibo** [comment]
Cool, glad it was an easy fix.
