### ISSUE TITLE
[SoundEffect] Apply3D and Stereo Buffers

### ISSUE THREAD

**Issue by mklingen** [FNA-XNA/FNA#112]
I have noticed that 3D sounds (whether mono or stereo) only work if `SoundEffectInstance.Play` is called *before* `SoundEffectInstance.Apply3D`, and further that stereo sounds will not work unless `Apply3D' is called *before* 'Play'. So to get XNA4-equivalent behavior of 3D stereo sounds, I have to do the following:

````
sound.Apply3D(listener, emitter);
sound.Play();
sound.Apply3D(listener, emitter);
````

The root issue seems to be that `INTERNAL_parentEffect.INTERNAL_monoBuffer` gets set inside *play*, but only *after* `Apply3D` is called. While Apply3D will only set the proper volume/position if `INTERNAL_alSource` is not `null`, which is only true after `sound.Play();` is called. So its a catch 22 -- Apply3D must be called both before and after `sound.Play()` for everything to be initialized.

**Comment by flibitijibibo** [comment]
I'm pretty sure this fixes it...

https://github.com/FNA-XNA/FNA/commit/a119246c4c11335b7c8f1e160b85cb975b50db6f

Can you check this real quick? This was definitely a bug but I don't have a test case for this.

**Comment by flibitijibibo** [comment]
A made-up case seems to work except for the stereo-to-mono case, but FWIW, save some disk space and mix the stereo effects down to mono. It lowers RAM use and avoids having to do a mixdown at runtime (which is not cheap!). I'll try to fix this in FACT, but for now the stereo-apply3d-after-play is kind of a WONTFIX because by the time we hit Apply3D on that stereo sound, the stereo buffer is already attached to the source and swapping out the buffers isn't easy to do without some audio cutout.

**Comment by mklingen** [comment]
You're right, sorry. This is on an out of date build.

**Comment by flibitijibibo** [comment]
Cool cool, I'll keep this open as a reminder for FACT. The TODO list for that one is really piling up...

**Comment by mklingen** [comment]
Nice, I'm glad that FACT seems to be humming along!
