### ISSUE TITLE
Application not closing on macOS

### ISSUE THREAD

**Issue by darfink** [FNA-XNA/FNA#118]
I'm using the latest master with a minimalistic hello world template on macOS.

Everything in general works flawlessly (playing sound, content loading etc), but the application does not close when I press the window's close button.

The library returns from the [`Game.Run`](https://github.com/FNA-XNA/FNA/blob/62288016c9b7ad0c6ece12d10483bb090eb9216d/src/Game.cs#L408-L426) method and executes the `Exiting` event callback, but after the game has finished executing and `DidFinishLaunching` returns, the application is stuck at `NSApplication.Main`.

I haven't been able to debug any further since it's library/native code, and Visual Studio (Xamarin) does not seem to provide that ability.

I recently switched to FNA from MonoGame, and this issue did not appear when using MonoGame, therefore I assume it's directly related to FNA.

* FNA - latest master
* Xamarin.Mac - 3.4.0.33
* Native libraries - tar from the [website](http://fna-xna.github.io/download/)

**Comment by flibitijibibo** [comment]
The solution is not to use MonoMac, and therefore not use NSApplication.Main. Use the path you use for your Windows version, strip out _all_ of the Xamarin tech you're using, and ship with MonoKickstart (and depending on where you got it from, save yourself a few hundred bucks):

https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games#mac-os-x

If you want to keep using MonoMac, you may want to file a report with Xamarin. I don't know if their binaries do this, but Ctrl+\ should provide a thread dump if you run the app from a terminal. The best guess I can make is that Xamarin's Mac runtime doesn't properly deal with ProcessExit, which we use here:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/FNAPlatform.cs#L85

**Comment by flibitijibibo** [comment]
It technically should work with those tools, but if they don't work then I don't know why. Speaking from half a decade of experience, it would not surprise me if the Xamarin tools deliberately overstepped their boundaries and broke other competing tools in favor of just using theirs instead. We were able to get the Xamarin runtime working with Transistor's SDL2 version for the [MAS](https://itunes.apple.com/us/app/transistor/id927617634?mt=12), but a lot can change in the 3 years that have passed since that game's release.

We work with a clean install of a vanilla runtime, including one built for macOS, so if it doesn't work with Hello World then you have a Xamarin problem on your hands.

**Comment by darfink** [comment]
Since the issue is not exhibited when using MonoGame with the same code base, do you still suspect it is related to Xamarin?

**Comment by flibitijibibo** [comment]
Absolutely. Please send a test build if you are still unsure.

**Comment by darfink** [comment]
Oh wow, this is awkward. I haven't programmed in C# for a long time, I've spent too much time using Rust. Anyway I asked myself if perhaps the game object implements the `IDisposable` interface, and sure as eggs are eggs it does.

Sorry for wasting your time, and thanks for an awesome framework!
