### ISSUE TITLE
Videoplayer texture corrupted when width power of two

### ISSUE THREAD

**Issue by bitstopper** [FNA-XNA/FNA#129]
I wanted to try the Videoplayer and downloaded Agent 327 from YouTube and cause I had to convert it anyway and the width was too wide (2048 x 858) I scaled it down by 50%. First I thought there was something else wrong but as I was trying out things it seems that when the video has no power of two width it plays correctly. Otherwise it looks like the attached screen.
![agent327_fna_test](https://user-images.githubusercontent.com/16385225/30227897-ba91c5bc-94db-11e7-8736-c0ec38a3c890.jpg)

**Comment by flibitijibibo** [comment]
I'll need the video file in question to look at this. Also, look at the YUV textures with apitrace:

http://apitrace.github.io/

**Comment by bitstopper** [comment]
I hope this works:
https://drive.google.com/open?id=0B_l0eSh67TiCWFozZWh3NXc5MlU

**Comment by flibitijibibo** [comment]
Took a look and I'm not entirely sure this is something we can (or should?) fix. The Y and U channels seem fine but V starts to get really weird because of that bad height value. For reference...

Y:
![mono-sgen trace_frame_44-0_0](https://user-images.githubusercontent.com/1396814/30229458-01d0e24a-94b0-11e7-90f3-9f446c39430a.png)

U:
![mono-sgen trace_frame_44-0_1](https://user-images.githubusercontent.com/1396814/30229465-08821406-94b0-11e7-9f4f-b2862e3655e6.png)

V:
![mono-sgen trace_frame_44-0_2](https://user-images.githubusercontent.com/1396814/30229468-0c7bf2de-94b0-11e7-8761-c1f784e7b338.png)

I'm tempted to just say "use the original res" as 2048 width/height isn't exactly a problem with today's hardware, and downscaling with the GL is probably a better idea than downscaling with something like ffmpeg (the quality of the test video kind of speaks for itself). More importantly, as far as I know this resolution isn't actually supported by XNA:

https://msdn.microsoft.com/en-us/library/dd254869.aspx

So that's that. See if you can't get a 1080p render of this straight from the source (surely the Blender Foundation has a Theora mirror somewhere...?) to get it to fit in a 16:9 environment.

If you're absolutely set on this resolution for whatever reason, you'll want to look at Theorafile's YUV buffer copy:

https://github.com/FNA-XNA/Theorafile/blob/master/theorafile.c#L487
