### ISSUE TITLE
Keyboard Up and Down events

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA#15]
Hi,

Firstly great work on this library, it's amazing how simple it has made it shifting an XNA application to multiple platforms.  

One difficulty I've come across though is the use of WinForms (and your recommendation not to for cross platform applications) and its usage in our application for accessing all the underlying keyboard events I.e. Getting access to all the key up and key down events (which we use for controlling a gui which uses control, alt, tab etc)

So I've looked into SDL2 and how I could use it to access those keyboard events and because FNA polls the events the only way I can see of accessing those events is to register an event filter using AddEventWatch.

I was wondering whether you thought exposing key up and down events as an extension to the XNA api would be something worthwhile?  The other option would be making the underlying SDL event stream available however that would tie FNA to SDL forever as a public api.

Many thanks,
Jeff

**Comment by flibitijibibo** [comment]
It would mostly depend of the cost of adding something like OnKeyDownEXT, since that does add some cycles to a critical XNA4 component, whereas something like TextInputEXT was almost entirely separate minus some control keys. This is definitely a common request though so I'll have to think about this again after MAG.

**Comment by flibitijibibo** [comment]
After thinking about this a little more I'm not sure I'd be willing to go for it.

The big reason is that the event loop covers so much more than just keys, and covering events for every single thing that XNA provided (unlike TextInputEXT where they totally ignored it) is just too much for us to maintain. It's a good case of "we're willing to fix XNA's gaps, but we can't make XNA good."

The way I _would_ design it is as a static InputEventsEXT extension, which would provide events for key down/up, mouse button down/up, gamepad button down/up, and so on. And you can see just how much would have to get tracked, in addition to all the _other_ things that each form of input might find valuable (including device add/remove events even).

Dumb as it sounds, it's probably _better_ to just track the events with SDL_AddEventWatch, because that way there aren't a good 2-3 layers acting as interference with what amounts to 2 if statements and lots of glitter that you can check out in the SDL_KeyboardEvent (glitter that FNA would never be able to cleanly provide):

https://wiki.libsdl.org/SDL_KeyboardEvent
https://wiki.libsdl.org/SDL_Keysym
https://wiki.libsdl.org/SDL_Keymod
