### ISSUE TITLE
Cannot load Microsoft.Xna.Framework.Game

### ISSUE THREAD

**Issue by nanodesu88** [FNA-XNA/FNA#220]
Hello!
I am creating new project, adding a FNA.dll referrence and taking 
```
System.TypeLoadException: Cannot load type "Mircosoft.Xna.Framework.Game" assembly "FNA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
```

code

```fsharp
open Microsoft.Xna.Framework

[<EntryPoint>]
let main argv = 
  use game = new Game()
  
  game.Run()
  
  0
```

.net framework 4.6.1/4.7.1
What can be wrong? 
Sorry, my english is very bad

**Comment by flibitijibibo** [comment]
Funnily enough the language I'm concerned about is the code's... what is that?

The assembly version is very strange, where did you get FNA.dll? It should be version 18.12.0.0 as of today; you can build this solution with VS:

http://fna.flibitijibibo.com/archive/FNA-1812.zip

**Comment by nanodesu88** [comment]
I tried to reference a FNA sources, not compiled dll and this error gets away. Any thoughts?

**Comment by flibitijibibo** [comment]
No idea why that happens, but referencing the csproj instead of the DLL is the recommended way to go anyway, since you'll be able to view the FNA source if something breaks internally.

Would be cool to know what really happened either way, but I'm not terribly concerned about it... glad it works now!
