### ISSUE TITLE
[Performance] Struct defense copies

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#227]
Hi, i noticed that FNA doesn't consider the fact that structs could make performance decrease.
I know that it's a context of nanoseconds, but why don't improve it?

I noticed that the operation between same vectors type makes defense copies when you access a non readonly field of the vector (X, Y ,Z).

https://github.com/FNA-XNA/FNA/blob/d103dce05d9f48dd0c1dba5ff5e4df4d333c5349/src/Vector3.cs#L1403

Method:
```csharp
                public static Vector3 operator +(Vector3 value1, Vector3 value2)
		{
			value1.X += value2.X;
			value1.Y += value2.Y;
			value1.Z += value2.Z;
			return value1;
		}
```

IL:
```
  .method public hidebysig static specialname valuetype Microsoft.Xna.Framework.Vector3 
    op_Addition(
      valuetype Microsoft.Xna.Framework.Vector3 value1, 
      valuetype Microsoft.Xna.Framework.Vector3 value2
    ) cil managed 
  {
    .maxstack 3
    .locals init (
      [0] valuetype Microsoft.Xna.Framework.Vector3 V_0
    )

    // [1404 3 - 1404 4]
    IL_0000: nop          

    // [1405 4 - 1405 25]
    IL_0001: ldarga.s     value1
    IL_0003: ldflda       float32 Microsoft.Xna.Framework.Vector3::X
    IL_0008: dup          
    IL_0009: ldind.r4     
    IL_000a: ldarg.1      // value2
    IL_000b: ldfld        float32 Microsoft.Xna.Framework.Vector3::X
    IL_0010: add          
    IL_0011: stind.r4     

    // [1406 4 - 1406 25]
    IL_0012: ldarga.s     value1
    IL_0014: ldflda       float32 Microsoft.Xna.Framework.Vector3::Y
    IL_0019: dup          
    IL_001a: ldind.r4     
    IL_001b: ldarg.1      // value2
    IL_001c: ldfld        float32 Microsoft.Xna.Framework.Vector3::Y
    IL_0021: add          
    IL_0022: stind.r4     

    // [1407 4 - 1407 25]
    IL_0023: ldarga.s     value1
    IL_0025: ldflda       float32 Microsoft.Xna.Framework.Vector3::Z
    IL_002a: dup          
    IL_002b: ldind.r4     
    IL_002c: ldarg.1      // value2
    IL_002d: ldfld        float32 Microsoft.Xna.Framework.Vector3::Z
    IL_0032: add          
    IL_0033: stind.r4     

    // [1408 4 - 1408 18]
    IL_0034: ldarg.0      // value1
    IL_0035: stloc.0      // V_0
    IL_0036: br.s         IL_0038

    // [1409 3 - 1409 4]
    IL_0038: ldloc.0      // V_0
    IL_0039: ret          

  } // end of method Vector3::op_Addition
```

Instead it should be:
```csharp
            public static Vector3 operator +(Vector3 value1, Vector3 value2)
            {
                   return new Vector3(value1.X + value2.X, value1.Y + value2.Y, value1.Z + value2.Z);
            }
```

IL:
``` 
  .method public hidebysig static specialname valuetype Microsoft.Xna.Framework.Vector3 
    op_Addition(
      valuetype Microsoft.Xna.Framework.Vector3 value1, 
      valuetype Microsoft.Xna.Framework.Vector3 value2
    ) cil managed 
  {
    .maxstack 4
    .locals init (
      [0] valuetype Microsoft.Xna.Framework.Vector3 V_0
    )

    // [1404 3 - 1404 4]
    IL_0000: nop          

    // [1405 13 - 1405 95]
    IL_0001: ldarg.0      // value1
    IL_0002: ldfld        float32 Microsoft.Xna.Framework.Vector3::X
    IL_0007: ldarg.1      // value2
    IL_0008: ldfld        float32 Microsoft.Xna.Framework.Vector3::X
    IL_000d: add          
    IL_000e: ldarg.0      // value1
    IL_000f: ldfld        float32 Microsoft.Xna.Framework.Vector3::Y
    IL_0014: ldarg.1      // value2
    IL_0015: ldfld        float32 Microsoft.Xna.Framework.Vector3::Y
    IL_001a: add          
    IL_001b: ldarg.0      // value1
    IL_001c: ldfld        float32 Microsoft.Xna.Framework.Vector3::Z
    IL_0021: ldarg.1      // value2
    IL_0022: ldfld        float32 Microsoft.Xna.Framework.Vector3::Z
    IL_0027: add          
    IL_0028: newobj       instance void Microsoft.Xna.Framework.Vector3::.ctor(float32, float32, float32)
    IL_002d: stloc.0      // V_0
    IL_002e: br.s         IL_0030

    // [1406 3 - 1406 4]
    IL_0030: ldloc.0      // V_0
    IL_0031: ret          

  } // end of method Vector3::op_Addition
```

I've done a simple and quick test with a Stopwatch:
```csharp
            Vector3 vec = new Vector3(1 , 2 ,3);
            Vector3 vec1 = new Vector3(7, 9, 5);

            Stopwatch sw = Stopwatch.StartNew();

            for (int i = 0; i < 100000000; i++)
            {
                Vector3 a = new Vector3(vec.X + vec1.X, vec.Y + vec1.Y, vec.Z + vec1.Z);
            }

            Console.WriteLine("new vector addiction: {0} ms", sw.ElapsedMilliseconds);

            sw.Restart();

            for (int i = 0; i < 100000000; i++)
            {
                Vector3 a = vec + vec1;
            }

            Console.WriteLine("only field addiction: {0} ms", sw.ElapsedMilliseconds);
```

CPU target: x64.
Windows 10 latest build.
8700k 4.8ghz

Results:
```
new vector addiction: 190 ms
only field addiction: 302 ms
```

There are a lot of structures utilization like vector in the FNA code, Vector3 is an example only :D

**Comment by flibitijibibo** [comment]
Get as many of these as you want and I’ll merge (as long as it’s clean of course). There’s no specific reason that we do this, it just happened to be written that way at the time.

**Comment by flibitijibibo** [comment]
This is all true; I would also add that regardless of what’s faster/slower, we definitely don’t act consistently across all the math types. We need to find out what’s actually better and run through all the functions to use the better result. Something tells me the answer won’t be the same every time (i.e. maybe it’s smarter to reuse a value within a local function, just not as a return value) but the reasons for each answer will at least make sense across all the types.

**Comment by andreakarasho** [comment]
Ok, i'll try :)

**Comment by bartwe** [comment]
In Staxel we have our own versions of these classes that took a different route i'd like to suggest you try out
{{{
        [TargetedPatchingOptOut("")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector3F operator +(Vector3F left, Vector3F right) {
            Vector3F result;
            result.X = left.X + right.X;
            result.Y = left.Y + right.Y;
            result.Z = left.Z + right.Z;
            return result;
        }
}}}

**Comment by nickgravelyn** [comment]
Regarding the attribute, it's simply a hint to the JIT to inline methods that exceed some limit (~32 bytes of IL at least as far as I can tell without actually diving into the JIT code itself) but still meet other requirements. It's not the best documented thing but there is this reference: https://dzone.com/articles/aggressive-inlining-clr-45-jit

Also there's probably a difference across different JIT implementations that might need accounting for. IIRC the Xbox 360 JIT also did better with code like the example @bartwe posted.

Also if you're going to do a lot of this type of benchmarking, it'd probably be good to ditch Stopwatch and use something like [BenchmarkDotNet](https://benchmarkdotnet.org) which is [in use](https://benchmarkdotnet.org/#our-users) by teams including the CoreCLR and Roslyn. That'll help get better numbers than most naive measuring tools.

**Comment by andreakarasho** [comment]
@bartwe the 
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
```

Influences the result, can you try to make inline my method also ?

**Comment by nickgravelyn** [comment]
I ended up quickly hacking together a simple benchmark for this to get some numbers: https://github.com/nickgravelyn/math-struct-benchmark. I pasted the results from my PC (.NET Core and .NET 4.6) as well as my MacBook Pro (.NET Core). I didn't spend time to hook up Mono but it would probably be a good addition since it is possible their JIT behaves differently.

The TL;DR is both approaches noted come out basically the same on my PC and MacBook and both are faster than what FNA has now for `operator +`. They also both work out about the same as the `Add(ref, ref, out)` static method.

And bizarrely Vector2 is a lot slower in all tests except for `Add(ref, ref, out)` for reasons I haven't bothered to dig into. So in that case the winner for raw performance is simply to use the static Add method with by-ref parameters.

**Comment by andreakarasho** [comment]
Hope to don't fall in error, but time ago i read that when you declare a raw struct variable, the 'new' operator is called internally.

**Comment by bartwe** [comment]
It is not. It is zero initialized but no constructor is ran.

Op vr 25 jan. 2019 09:05 schreef Andrea Angelini <notifications@github.com:

**Comment by nickgravelyn** [comment]
This morning I got the benchmarks to run on .NET Core, .NET Framework, and Mono, plus I added versions that use the aggressive inlining hints. Results/takeaways from my PC are updated in the repo: https://github.com/nickgravelyn/math-struct-benchmark

One you put Mono in the mix, then @bartwe's solution is generally the better approach as it's no slower on any platform and generally out-performs on Mono. 

And the static Add method with by-ref parameters continues to be the best approach for raw performance across all runtimes, particularly on Mono where it's consistently 2x+ faster than any of the operators.

**Comment by bartwe** [comment]
👍 🥇

**Comment by nickgravelyn** [comment]
So because I couldn't actually let go of why 2D vectors were so bad, I created an [isolated benchmark](https://github.com/nickgravelyn/math-struct-benchmark/tree/vector2-focus) which shows that RyuJIT is actually doing some automatic SIMD instructions but generates quite poor SIMD instructions for the 2D vector versus the 3D vector. 

This lines up with another result, which is that the 32-bit legacy JIT is actually faster than RyuJIT for Vector2 because it doesn't attempt automatic SIMD generation. So this is actually something of a performance regression in their JIT code generation.

So to reiterate: while @bartwe's + operator is the most efficient, particularly with 2D vectors on the modern JIT it's actually far more optimal to stick to the static Add method if raw performance is critical (e.g. inside a 2D physics engine or perhaps down in some core rendering loops).

**Comment by nkast** [comment]
A problem with using the static methods is that it's hard to read.

Is it possible to write a post-build tool to replace operators (+-*/) with static methods?
With a tool  like Mono.Cecil we could replace the method call and convert struct.copies to struct refs on the IL level.

**Comment by nickgravelyn** [comment]
At least with newer C# you can inline the output variable:

```csharp
Vector2.Add(ref b, ref c, out var a);
```

But yeah it's not as easy to read, especially if you're trying to convert something like `var result = a + b * 2` or whatever into the static methods.

I'm sure with Cecil you could rewrite the operators into the static calls. The trickiest part would be managing temporary results which would end up with the process needing some additional locals. In the `var result = a + b * 2` example you'd end up with something like:

```csharp
Vector2.Multiply(ref b, 2, out var temp1);
Vector2.Add(ref a, ref temp1, out var result);
```

And if you end up with more and more temporaries you end up with more and more intermediate structs. Not necessarily a problem (and fairly similar to register assignment which can be optimized) but it does make this not quite a trivial operation.

**Comment by bartwe** [comment]
When performance needs beat using the clarity of the operators on Vector3 it is generally better to just manually inline and have separate local x,y,z variables. 
I did a bunch of experiments with writing an il optimizer (using among other things, cecil) and while the end results is naively shorter and better the jit does a worse job by being a bit unlike the normal compiler output.

**Comment by nickgravelyn** [comment]
Well if you toss that out you know I just have to add it to the benchmark. 😄 

I updated my benchmarks to remove the slowest three cases and add one for local floats. Based on the benchmarks the separate local fields is only faster than the by-ref Add method on Mono. My assumption is that both RyuJIT and LegacyJIT are able to fully inline and optimize down to comparable assembly (though I haven't actually checked) while Mono isn't quite as good. And interestingly when you're looking at Vector4 on Mono you finally have a reason to prefer System.Numerics.Vector4 which is faster on both 32- and 64-bit than all other approaches, including the local fields (though not by much).

As far as changes to FNA, it seems it would be beneficial to change all the vector operators and functions that aren't by-ref to ensure they use a local for the result, rather than modifying the parameters and are marked for aggressive inlining. I might also consider benchmarking whether it makes sense to simply have all non by-ref functions delegate to the by-ref versions internally as I would expect that to get inlined by the JIT all the same and reduce the duplication of IL, but at this point even my own assumptions aren't worth trusting given all the weird things I've found benchmarking this stuff.

It'd also be good to benchmark things like Matrix since it's 4x the size of Vector4, and see if the operators there hold the same pattern or if a different approach would be necessary given the extra size and instruction count.

**Comment by nkast** [comment]
I build a small prototype with Cecil. 
The only thing it does at the moment is it replaces the sequence of IL instructions

```
.Ldloc n
.Call Vector2 Vector2.op_Addition(Vector2,Vector2)
```
with 
```
.Ldloca n
.Call Vector2 Vector2.Add_vrv(Vector2, ref Vector2)
```

This is the same as rewriting `Vector2 r=a+b;` into `Vector2 r= Vector2.Add_vrv(a,ref +b);` in C# code.

I put it up on GitHub here.  The results so far are surprisingly good.
https://github.com/nkast/PostOpt.Net/commit/a9e0ea9d8b3fba7e3a1e21b21985e0a058afe8a2

**Comment by oroechimaru** [comment]
any updates?

**Comment by flibitijibibo** [comment]
Looks like this bug hit the 1-year mark without any patches... I think this is all we got:

- Math ops that don't use `new` for the return value are slow
- Just about everything else is hard to measure, especially with multiple runtimes

I'll still take patches for this, but it seems like it hasn't been important enough for anyone to sit down and scan through the Math structs to make the changes. There's some discussion going on in the Discord if someone wants to get this before 20.01, but until we get a really bad performance case it doesn't seem necessary to have a generic tracker filed.
