### ISSUE TITLE
Help with stencil

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#228]
Hi,

How can i translate this code?

```cpp
glColorMask(false, false, false, false);

    glStencilFunc(GL_ALWAYS, 1, 1);
    glStencilOp(GL_KEEP, GL_KEEP, GL_REPLACE);

    g_GL.DrawPolygone(m_X, m_Y, Width, Height);

    glColorMask(true, true, true, true);

    glStencilOp(GL_KEEP, GL_KEEP, GL_KEEP);
    glStencilFunc(GL_NOTEQUAL, 1, 1);
```
My FNA translation is:

Stencil
```csharp
DepthStencilState state = new DepthStencilState();

            state.DepthBufferEnable = false;
            state.StencilEnable = false;

            state.StencilFunction = CompareFunction.Always;
            state.ReferenceStencil = 1;
            state.StencilMask = 1;

            state.StencilFail = StencilOperation.Keep;
            state.StencilDepthBufferFail = StencilOperation.Keep;
            state.StencilPass = StencilOperation.Replace;

            state.TwoSidedStencilMode = false;

            return state;
```

Blend:
```csharp
 BlendState blend = new BlendState();
            blend.ColorWriteChannels = ColorWriteChannels.Alpha;
            return blend;
```

Draw function:
```csharp
batcher.SetBlendState(_checkerBlend.Value); // is a lazy, set and flush
            batcher.SetStencil(_checkerStencil.Value); // is a lazy , set and flush

// TransparenTexture is a Color.Black texture with alpha = .5f
            batcher.Draw2D(TransparentTexture, new Rectangle(position.X, position.Y, Width, Height));

            batcher.SetBlendState(null); , // restore old blend and flush
            batcher.SetStencil(null); , //restore old stencil and flush
```

The final result doesn't apply the alpha to the textures drawn before.

Mine:
![image](https://user-images.githubusercontent.com/20810422/50663567-5a93bf80-0faa-11e9-9940-bb36ec0c9f87.png)

Expected:
![image](https://user-images.githubusercontent.com/20810422/50663522-33d58900-0faa-11e9-9176-3b4e87ea4e87.png)

**Comment by flibitijibibo** [comment]
`blend.ColorWriteChannels` should be `0`, right?

If you want a sense of how the pipeline state maps to the GL call stream, you can either look at the OpenGLDevice's implementation of these functions...

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/GraphicsDevice.cs#L1437

... or you can apitrace both to see where the GL state mismatches. Because XNA pipeline state covers everything at once there may be an assumption about certain states that the GL version ignores while XNA will submit a call that doesn't match.

**Comment by andreakarasho** [comment]
Partially resolved
