### ISSUE TITLE
ArgumentOutOfRangeException SDL2_FNAPlatform.PollEvents

### ISSUE THREAD

**Issue by bartwe** [FNA-XNA/FNA#336]
System.ArgumentOutOfRangeException Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress)
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()

**Comment by bartwe** [comment]
Once in a while a user bug report contains this. unsure of the cause, the code looks correct.

**Comment by flibitijibibo** [comment]
All array accesses:

- https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L759
https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1022
https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L913

The first two are well-guarded, you can only get there with index values that are valid. The latter is the only odd one since you can get display events that may change the adapter order:

https://hg.libsdl.org/SDL/file/fad35e813902/include/SDL_video.h#l179

We're talking about hotplugging monitors during runtime though, which seems unlikely.

**Comment by bartwe** [comment]
I can imagine a quick connect/disconnect pair, due to the queued/delayed/async nature of processing events, having a value that would not be valid.
