### ISSUE TITLE
DotNET Core compatibility.

### ISSUE THREAD

**Issue by tapir** [FNA-XNA/FNA#34]
Is it possible to build FNA with the newly released .NET Core 1.0?

Can we get a project.json file to build it or at least a .NET Core compiled NuGet packaged so that we can import it easily?

Thanks

**Comment by flibitijibibo** [comment]
Right now we're only targeting .NET 4.0-4.6 due to Core's poor native interop support (see: https://github.com/flibitijibibo/SDL2-CS/pull/93 )

I'd like to get FNA working with CoreCLR if only to scrap Mono from my environment, but it seems to require breaking compatibility with absolutely everything else while also making the interop much MUCH worse, which amazingly manages to not be worth scrapping Mono for.

I'll be looking at it when CoreCLR improves, because I REALLY want Mono to go away, but right now it's missed pretty much every checkbox I had on the list.

**Comment by tapir** [comment]
Does CoreCLR 2.0 makes this any different?

**Comment by flibitijibibo** [comment]
The dropping of the weird new project format over msbuild is the only improvement I'm aware of, I don't think anything else really improved for us.

**Comment by tapir** [comment]
how about 3.1?

**Comment by flibitijibibo** [comment]
netstandard20 works fine now, use Core.csproj for that. .NET Core still pretty much failed to do anything that I was expecting it to do, but I ended up adding support to make Xbox builds work.
