### ISSUE TITLE
Exit() hangs indefinitely

### ISSUE THREAD

**Issue by Stay1444** [FNA-XNA/FNA#416]
Windows 10. .NET 7. 
Rendering backend: Hapens in both D3D11 and Vulkan.

**Comment by flibitijibibo** [comment]
Stack traces will help identify where the waiting occurs!

**Comment by Stay1444** [comment]
Yep sorry. I'm not sure on how to do that. Code after Game#Run() is running fine. Following the Exit() function in the debugger, everything appears to execute good without any hangs or exceptions. But for some reason the stack trace only shows the main function.

**Comment by flibitijibibo** [comment]
Hard to say... usually that means a thread got stuck somewhere? We don't allocate any managed threads so that would be my first place to look. Old systems were more tolerant of threads not exiting after main exits but this has become less true over time (and I don't think it was ever true when using Mono).

You may also get better results using Framework 4.6.2 rather than 7, as we only support Framework on desktop: https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#i-have-a-bug-when-running-on-net-core-and-

**Comment by Stay1444** [comment]
Yeah Rider's debugger does not show any other threads running. That would probably be because they are not managed threads like you said. 

Switching over to .NET Framework is not really an option. 

If i enable NativeAOT it works fine. Ill do a dirty Process.GetCurrentProcess().Kill() with some timeout or something on debug mode.
