### ISSUE TITLE
Add support for ContentManager's ReadAsset function to read from custom streams instead of only on the disk

### ISSUE THREAD

**Issue by ClementineAccount** [FNA-XNA/FNA#438]
This just an issue page that is based off the comment found in [ContentManager.cs](https://github.com/FNA-XNA/FNA/blob/c68f7d938e9e6c967ce2ed51e249293d4ee76a62/src/Content/ContentManager.cs#L281C79-L281C79) which is shown as
```
// Okay, so we couldn't open it. Maybe it needs a different extension?
// FIXME: This only works for files on the disk, what about custom streams? -flibit
modifiedAssetName = MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators(
	Path.Combine(RootDirectoryFullPath, assetName)
```	

I don't see an issue already listing it, so I am creating this so it doesn't get forgotten.

**Comment by flibitijibibo** [comment]
I _think_ the fix is to do the same process but instead of querying the filesystem we have to take the Stream's "path" (or check the type maybe...?) and try to normalize that, or if the Stream is already valid, peek a few bytes to determine the type (which I think we do, but in a different part of the reading process).

**Comment by flibitijibibo** [comment]
Took another look, we'll need to expand this functionality...

https://github.com/FNA-XNA/FNA/blob/master/src/Content/ContentTypeReader.cs#L69

... to check with the ContentManager's Open function, probably by passing the function pointer.

**Comment by flibitijibibo** [comment]
Does this commit resolve the issue?

https://github.com/FNA-XNA/FNA/commit/fb3f62e9b5495ad2ce252b1b8be1c884817395b8
