### ISSUE TITLE
XACT Pitch/Volume Variation does not work with looped sound effects.

### ISSUE THREAD

**Issue by teamtwentythree** [FNA-XNA/FNA#45]
Creating an XACT sound effect with pitch and volume variation enabled works ok.  But if you make the effect looped, then the pitch/volume is randomized once when you play the cue, and then never again for the subsequent looped plays.  

In looking at the code it appears the looping is handled by OpenAL, but the variation only happens with creation of the SoundEffectInstance in CueData.GenerateInstance.  That said I don't have my head wrapped around the sound system at this point, so my assumptions could be incorrect.

Not a blocking issue for us, since we can just yank the looping and loop in code, but is an XNA accuracy issue.

**Comment by flibitijibibo** [comment]
As far as I can tell both are handled at loop time. What happens is that the current instance plays out...

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/Cue.cs#L503

... then we play the wave again...

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/Cue.cs#L899

... and from there, the pitch/volume are again randomly made, since as far as the CueData is concerned it's a totally new sound, with a check for when the max loopcount is hit:

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/CueData.cs#L837

Note that the AL only does looping if the XACT data indicates both an infinite loop as well as no variation data, as determined at parse time:

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/CueData.cs#L426

You will need to either see if other event types found at parse time have indicators for variation on loop, or determine if there are additional checks needed for avoiding AL loops.

**Comment by teamtwentythree** [comment]
Sound with looping set to infinite repros, setting it to 254 and the repro goes away.  

I was able to fix it by updating https://github.com/FNA-XNA/FNA/blob/master/src/Audio/CueData.cs#L525

I just replaced false with `minVolume != maxVolume || minPitch != maxPitch`

That said I'm not sure what these different events are, so not sure if that fix is correct or not.

**Comment by flibitijibibo** [comment]
That makes sense to me, but what happens if you disable variation on loop for that Cue in the XACT tool? Is it still the same event type? If it falls to the next type that has the known bool, I'm willing to write that fix in and call it a day!

**Comment by flibitijibibo** [comment]
I need the above test verified today if it's going into FNA 16.08.

**Comment by flibitijibibo** [comment]
There's MUCH more to this than I was expecting.

There is indeed a check for variation types, but it depends on the type of variation and which thing is varying. So, take this XACT data for example:

http://www.flibitijibibo.com/Win.zip

- VYPY is volume variation on loop and pitch variation on loop.
- VYPN is volume variation on loop and pitch variation fixed.
- VNPY is volume variation fixed and pitch variation on loop.
- VYPYADD is volume variation and pitch variation with add instead of replace.

The data for these are stored here:

https://github.com/FNA-XNA/FNA/blob/master/src/Audio/CueData.cs#L510

Here's the hex output:

- VYPN: 0x3200
- VNPY- 0x3100
- VYPY - 0x3300
- VYPYADD - 0x3304

No idea what the upper 4 bits are, but the second 4 bits are for variation on loop for vol/pitch/freq/qfactor, and the lower 4 bits appear to be tied to add/replace for variation loops. Also dunno what the third set of bits are.

This is going to take more time, so let's skip this for 16.08 and look at it for 16.09.

**Comment by flibitijibibo** [comment]
Does this commit do it?

https://github.com/FNA-XNA/FNA/commit/d5d7d6346adc40c4a1691a3c68faf054fbf85098

**Comment by teamtwentythree** [comment]
Knee deep in multiplayer bugs today, I should be able to test tomorrow and confirm fix.

**Comment by teamtwentythree** [comment]
This works for our test case.  Infinite sound, pitch and volume variation enabled.

**Comment by flibitijibibo** [comment]
Cool, this might get interesting depending on how we solve loops, but for now...!
