### ISSUE TITLE
Multiple window extension?

### ISSUE THREAD

**Issue by RobJellinghaus** [FNA-XNA/FNA#54]
I have a C# project that uses Kinect for Windows (the new one) to implement a gesturally controlled audiovisual live looper:  http://holofunk.com

This project was originally written with XNA, then ported to the SharpDX Toolkit (an XNA-like layer on top of SharpDX with DirectX 10).  Now, with Windows 10, DX10 is dead and gone, and the SharpDX Toolkit is no longer maintained.

Along comes FNA, answer to my prayers!  Except: my app creates and renders multiple views in multiple windows (to provide multi-monitor support, whereby a monitor and a projector can be displaying different rendered views of the same performance).  

It appears right now that FNA supports only one GameWindow, via the singleton Game.Window property.  The SharpDX Toolkit added support for multiple GameWindowRenderers, which my app uses.  FNA loses this.

Is it conceivable that I might add an extension to FNA which supports multiple windows?  I would be happy to create a pull request with a working example.  Also even happier to hear any design feedback or offhand thoughts about this idea.

Thanks very much!
Cheers,
Rob Jellinghaus

**Comment by flibitijibibo** [comment]
It will be less work for you to use multiple SDL_Window* handles directly and wire them to two GraphicsDevices then it will be to staple an extra GameWindow into the XNA Game design. The GameWindow and Game were deliberately designed to only give users a single window and a game loop, and that was it - even by their own recommendation it's better to self-build multiple windows and graphics contexts, because the Game structure is so limited.

Odds are, whatever you're doing that requires multiple windows is a little bit smarter than what the XNA design can provide, no matter how many extensions you add.
