### ISSUE TITLE
FNAPlatform.CreateWindow() And NativeLibs Win10(?) malfunction.

### ISSUE THREAD

**Issue by Fenrisus** [FNA-XNA/FNA#62]
Hello. I am using Windows10, and just take a source code, and native libs from new version and got a strange behavior. They show me nothing without any errors on MSVS Debugger. 

Well, step by step.
1)Compiling output:
![debug](https://cloud.githubusercontent.com/assets/3074538/19188543/0701e980-8c9b-11e6-9606-c26bfe0c86b3.png)
2)then launch application:
![debug2](https://cloud.githubusercontent.com/assets/3074538/19188560/235615d4-8c9b-11e6-81f0-90f5f341f3f1.png)
And nothing... and after short time, they simple close and exit running state.
Well, next i am running them with step in. For be short, before "do nothing" and exit thread my last step is:
![debug4](https://cloud.githubusercontent.com/assets/3074538/19188608/86bc440e-8c9b-11e6-8090-a830942d8e6a.png)
Debug output in this case is:
![debug3](https://cloud.githubusercontent.com/assets/3074538/19188613/8d378320-8c9b-11e6-9ba8-ef9e4f659303.png)

But i dont see any error!

Also my sample folder contains those files:
![debug5](https://cloud.githubusercontent.com/assets/3074538/19188628/a6f0b502-8c9b-11e6-8ab5-7fb2e7e74977.png)

If i am try to change native libs to any other - they simple crush (with exeption) on spriteBatch = new SpriteBatch(GraphicsDevice); But with libs from http://fna-xna.github.io/download/
no any error.  Based on StepIn(F11) debug running, something going wrong on public class Game : IDisposable--------->Window = FNAPlatform.CreateWindow();
But there is no any error.

Any solution/suggestion?

**Comment by flibitijibibo** [comment]
The fnalibs are required because the Visual Studio debugger has problems with how native libs do thread naming. Don't use official releases just yet.

**Comment by flibitijibibo** [comment]
Reading this again, are you saying with fnalibs and 16.10 that it exits on the debugger anyway?

**Comment by flibitijibibo** [comment]
One more post, just to be 100% clear:

Using fnalibs.tar.bz2 and FNA 16.10 it is possible to run an FNA game on VS2010 with the debugger on. If you change this line to 0...

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L65

... then vshost will crash, since a thread is being named and the debugger likes catching the native thread name exception.

If you were to use the stock SDL2.dll from libsdl.org, you would get the latter result. Only the fnalibs archive has the functioning DLL, as the environment variable has not been mainlined into SDL Hg yet. Similarly, if you use any FNA version before 16.10 with the current fnalibs archive, you will get the latter result since we're not setting this environment variable.

To work around Visual Studio's bug, you _must_ use FNA 16.10 (or newer) and you _must_ use the latest fnalibs.
