### ISSUE TITLE
Runtime Shaders implementation.

### ISSUE THREAD

**Issue by Fenrisus** [FNA-XNA/FNA#63]
1) Why not additional runtime shader compilation support, via MojoShader on Windows/Linux/Mac platforms?
2)How about this? https://blogs.msdn.microsoft.com/chuckw/2012/05/07/hlsl-fxc-and-d3dcompile/
3)How about GLSL shaders compilation & support? (for example, how compile them without pipeline and DirectX tool?)

In fact - d3d9 compiler is outdated(but still usefull), but there is some things with shaders on FNA without using content pipeline. How about something like MGFX (but, oh no, don't back to it!) but more light & clean based on Mojoshader & SDL2?

Compatibility with XNA 4.0 is should be, but nowadays on our reality, imho we need something more and more flexible than install Game Studio or download DirectX **C++** (not C# mainly) SDK for development games on C# with XNA 4.0 **coding** API.  On my vision (just my vision) main feature is coding API, content management implementation - is just all about processing game content. Guess nothing will happens if something like Effect.CompileEffectFromSource() is back from XNA 3.0 (those function has been removed just because XBox does not support runtime shader compilation - stupid MS reason for remove them **for all platforms** and move those to EffectProcessor inside their pipeline. (if following their logic, why not remove Texture2D.FromFile? haha) ).

That will be great, if FNA going to more flexible way on that direction. Maybe in long time future, but that will be really nice to see those feature on FNA.

**Comment by flibitijibibo** [comment]
1 + 2. If you want to write the compiler, you'll have to start here:

https://hg.icculus.org/icculus/mojoshader/file/6dd73a80629b/mojoshader_preprocessor.c
https://hg.icculus.org/icculus/mojoshader/file/6dd73a80629b/mojoshader_compiler.c

Keep in mind that you're not writing any old compiler; it must be accurate to FXC.

3. No. At most I would only ever add SPIR-V support since it's easy to reassemble into various shader languages. If you want to understand the difficulty of multilanguage translation, see points 1+2.

If you want to write a compiler, go for it. If it gets into mainline MojoShader we could even include Effect.FromSourceEXT and not really change any code aside from the addition of that method, but you're probably better off just keeping a copy of FXC around. Keep in mind that if you really wanted to you could add Shader Model 4/5 support to MojoShader and keep the same Effects code in FNA, and get modern shader features (including other shader stages like geometry/tesselation), and still use FXC to build shaders that remain compatible with us. That, at least, would be an incremental step in expanding shader support, but starting off with "just" a compiler is an _extremely_ bad idea.

The main point is: FNA is a runtime library, not a large set of tools. MGFX was abandoned not only because it had bad compatibility, but because it was an extra tool that made XNA4 preservation difficult since we're focusing on things that are not strictly in the realm of XNA preservation. Writing SM4/SM5 bytecode compatibility, in addition to writing an HLSL/D3DFX compiler, are well beyond the scope of mere XNA preservation, and should be treated as their own projects. It's a project we need, no doubt, but not strictly in our case. Even the inclusion of XACT as a subsystem of FNA, rather than as a separate native library, ended up being a pretty big mistake that I still regret. I'm not doing that again.

I'm closing this only because it's not an FNA issue; it's a MojoShader issue. That should be where you're focused.

**Comment by Fenrisus** [comment]
Just a little question after. Maybe there is some point of interest? How about this for example?

```
		public const int GL_FRAGMENT_SHADER = 0x8B30;
		public const int GL_VERTEX_SHADER = 0x8B31;
		public const int GL_GEOMETRY_SHADER = 0x8DD9;
//....blahblahblah
		public static CreateShader CreateShader;
//...blahblahblah
           //usage:
            var vertexHandle = GL.CreateShader (GL.GL_VERTEX_SHADER);
	    var fragmentHandle = GL.CreateShader (GL.GL_FRAGMENT_SHADER);
            GL.ShaderSource(vertexHandle, vertex_source);
            GL.ShaderSource(fragmentHandle, fragment_source);
            GL.CompileShader(vertexHandle);
```
And our little custom shader.
```
#version 140

in vec3 vertex_position;
in vec3 vertex_normal;
in vec2 vertex_texture1;

out vec3 e;
out vec3 n;
out vec3 world_position;
out vec3 out_normal;
out vec3 view_position;

uniform mat4x4 World;
uniform mat4x4 View;
uniform mat4x4 ViewProjection;
uniform mat4x4 NormalMatrix;
uniform vec3 CameraPosition;

void main()
{
	vec4 pos = (ViewProjection * World) * vec4(vertex_position, 1.0);
	gl_Position = pos;

	vec4 p = vec4(vertex_position, 1.0);

	e = normalize(vec3(View * World * p));
	n = normalize(vec3(NormalMatrix * vec4(vertex_normal, 0.0)));
	out_normal = (NormalMatrix * vec4(vertex_normal, 0.0)).xyz;
	world_position = (World * vec4(vertex_position, 1.0)).xyz;
	view_position = (View * World) * vec4(vertex_Position,1);
}
```
Originally XNA does not support shaders like that. *.vs, *.frag *.inc  But GL.CreateShader &  GL.ShaderSource bindings on FNA for GL seems missed up...(yeah i know, seems like i begging for Runtime **GL shaders** compilation hehe) Hmm, seems non hard to implement those GL calls on FNA "low level" GLDevice API, and for example, this can be used on custom Shader class outside FNA.dll in project. Is possible to enable those GL functions on official FNA trunk? ;)

**Comment by flibitijibibo** [comment]
>Is possible to enable those GL functions on official FNA trunk?

No, not without writing extensions that I have no intention of integrating into FNA. Don't take shortcuts, do it right or don't do it at all.
