### ISSUE TITLE
Any thoughts on BGFX?

### ISSUE THREAD

**Issue by raizam** [FNA-XNA/FNA#65]
https://github.com/bkaradzic/bgfx
https://github.com/MikePopoloski/SharpBgfx

Would it be a good idea to use bgfx to implement all the rendering?

**Comment by flibitijibibo** [comment]
Doesn't seem compatible, so probably not. You can write BGFXDevice if you want but I'm guessing their shader subsystem will get in your way quickly.

**Comment by raizam** [comment]
@flibitijibibo  Their shader translator is design time only. At runtime, the API takes compiled HLSL or GLSL

**Comment by flibitijibibo** [comment]
I closed it mostly because nobody is going to write it. And if someone _is_ going to write it, they'll need a pull request instead. I avoid leaving issues like this one open to avoid giving anyone false hopes.

**Comment by raizam** [comment]
I'm smart enough to understand the real issue is elsewhere. You did give a single argument.
Who is having hopes, here besides me?

Such a Pull Requests would be useless, because you would refuse it.

**Comment by flibitijibibo** [comment]
I'd be up for a pull request, since in theory all the work would be done and I could just merge it. The IGLDevice would make it easy to review too, since a BGFX device wouldn't touch anything outside of SDL2_FNAPlatform.

But again, I'm not going to write it, so this isn't on the roadmap for mainline FNA. Someone else will have to write it, and whether or not this is open should have no effect on you writing BGFXDevice.

I really strongly suggest reading up on the FNAPlatform folder and assessing this for yourself, I'm sure you'll do just fine after that.

**Comment by raizam** [comment]
Thank you for the tip, the project is clean and well organized, very easy to browse.
I'll give some thoughts and see if I can spend time on such project.

Thanks

**Comment by raizam** [comment]
The good news is that BGFX already implements SDL2 integration.

The bad news is that BGFX doesn't give control on draw order, and sorts draw call internaly. 
In order to draw overlays, it is possible to assign different draw calls to different queues.
But all this introduce some incompatibilities with the XNA api.

Hence if such integration would be done, there would be breaking changes, which makes it out of scope of FNA I guess.
Still it could make a very nice fork, now I'm not sure I have the right profil for such challenge.
